/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef ENTITY_BROWSER_BAKE_CONFIG_H
#define ENTITY_BROWSER_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_meta.h>
#include <flecs_components_http.h>
#include <flecs_systems_rest.h>
#include <flecs_systems_civetweb.h>

/* Headers of private dependencies */
#ifdef ENTITY_BROWSER_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef ENTITY_BROWSER_STATIC
  #if ENTITY_BROWSER_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define ENTITY_BROWSER_EXPORT __declspec(dllexport)
  #elif ENTITY_BROWSER_IMPL
    #define ENTITY_BROWSER_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define ENTITY_BROWSER_EXPORT __declspec(dllimport)
  #else
    #define ENTITY_BROWSER_EXPORT
  #endif
#else
  #define ENTITY_BROWSER_EXPORT
#endif

#endif

