/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef FLECS_DASH_BAKE_CONFIG_H
#define FLECS_DASH_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_meta.h>
#include <flecs_components_http.h>
#include <flecs_systems_rest.h>
#include <flecs_systems_civetweb.h>

/* Headers of private dependencies */
#ifdef FLECS_DASH_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef FLECS_DASH_STATIC
  #if FLECS_DASH_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define FLECS_DASH_EXPORT __declspec(dllexport)
  #elif FLECS_DASH_IMPL
    #define FLECS_DASH_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define FLECS_DASH_EXPORT __declspec(dllimport)
  #else
    #define FLECS_DASH_EXPORT
  #endif
#else
  #define FLECS_DASH_EXPORT
#endif

#endif

